# Database options
database:
  name: tickets-api
  username: postgres
  password: password
  addr: localhost:5432 # Use postgres:5432 if the API is running inside a container

# API service options
api_service:
  port: 8080
