definitions:
  models.CreateRequest:
    properties:
      allocation:
        type: integer
      desc:
        maxLength: 500
        type: string
      name:
        maxLength: 100
        minLength: 5
        type: string
    required:
    - allocation
    - name
    type: object
  models.FailureResponse:
    properties:
      error:
        type: string
      message:
        type: string
    type: object
  models.PurchaseRequest:
    properties:
      quantity:
        type: integer
      user_id:
        type: string
    required:
    - quantity
    - user_id
    type: object
  models.Ticket:
    properties:
      allocation:
        type: integer
      desc:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /tickets:
    post:
      consumes:
      - application/json
      description: This endpoint creates a new ticket by providing name, description,
        and allocation.
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Ticket creation input
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.CreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created ticket details
          schema:
            $ref: '#/definitions/models.Ticket'
        "400":
          description: Error message including details on failure
          schema:
            $ref: '#/definitions/models.FailureResponse'
      summary: CreateTicket creates a new ticket
      tags:
      - tickets
  /tickets/{id}:
    get:
      consumes:
      - application/json
      description: Retrieves a ticket from the database by its ID.
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: ID of the ticket
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Details of the requested ticket
          schema:
            $ref: '#/definitions/models.Ticket'
        "400":
          description: Error message including details on failure
          schema:
            $ref: '#/definitions/models.FailureResponse'
      summary: Get a ticket by ID
      tags:
      - tickets
  /tickets/{id}/purchase:
    post:
      consumes:
      - application/json
      description: This endpoint purchases a new ticket by providing id and quantity.
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Ticket purchase input
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.PurchaseRequest'
      produces:
      - application/json
      responses:
        "204":
          description: Purchase successful, no content
        "400":
          description: Error message including details on failure
          schema:
            $ref: '#/definitions/models.FailureResponse'
      summary: PurchaseTicket purchases a new ticket
      tags:
      - tickets
swagger: "2.0"
